nodes:
  - name: RBS::AST::Annotation
    builds_ruby_object_internally: true
    fields:
      - name: string
      - name: location
  - name: RBS::AST::Comment
    fields:
      - name: string
      - name: location
  - name: RBS::AST::Declarations::Class
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type_params
      - name: super_class
      - name: members
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Declarations::Class::Super
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: args
      - name: location
  - name: RBS::AST::Declarations::ClassAlias
    builds_ruby_object_internally: true
    fields:
      - name: new_name
      - name: old_name
      - name: location
      - name: comment
  - name: RBS::AST::Declarations::Constant
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: location
      - name: comment
  - name: RBS::AST::Declarations::Global
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: location
      - name: comment
  - name: RBS::AST::Declarations::Interface
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type_params
      - name: members
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Declarations::Module
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type_params
      - name: self_types
      - name: members
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Declarations::Module::Self
    fields:
      - name: name
      - name: args
      - name: location
  - name: RBS::AST::Declarations::ModuleAlias
    builds_ruby_object_internally: true
    fields:
      - name: new_name
      - name: old_name
      - name: location
      - name: comment
  - name: RBS::AST::Declarations::TypeAlias
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type_params
      - name: type
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Directives::Use
    builds_ruby_object_internally: true
    fields:
      - name: clauses
      - name: location
  - name: RBS::AST::Directives::Use::SingleClause
    fields:
      - name: type_name
      - name: new_name
      - name: location
  - name: RBS::AST::Directives::Use::WildcardClause
    fields:
      - name: namespace
      - name: location
  - name: RBS::AST::Members::Alias
    builds_ruby_object_internally: true
    fields:
      - name: new_name
      - name: old_name
      - name: kind
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Members::AttrAccessor
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: ivar_name
      - name: kind
      - name: annotations
      - name: location
      - name: comment
      - name: visibility
  - name: RBS::AST::Members::AttrReader
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: ivar_name
      - name: kind
      - name: annotations
      - name: location
      - name: comment
      - name: visibility
  - name: RBS::AST::Members::AttrWriter
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: ivar_name
      - name: kind
      - name: annotations
      - name: location
      - name: comment
      - name: visibility
  - name: RBS::AST::Members::ClassInstanceVariable
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: location
      - name: comment
  - name: RBS::AST::Members::ClassVariable
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: location
      - name: comment
  - name: RBS::AST::Members::Extend
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: args
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Members::Include
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: args
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Members::InstanceVariable
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: type
      - name: location
      - name: comment
  - name: RBS::AST::Members::MethodDefinition
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: kind
      - name: overloads
      - name: annotations
      - name: location
      - name: comment
      - name: overloading
      - name: visibility
  - name: RBS::AST::Members::MethodDefinition::Overload
    fields:
      - name: annotations
      - name: method_type
  - name: RBS::AST::Members::Prepend
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: args
      - name: annotations
      - name: location
      - name: comment
  - name: RBS::AST::Members::Private
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::AST::Members::Public
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::AST::TypeParam
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: variance
      - name: upper_bound
      - name: default_type
      - name: location
  - name: RBS::MethodType
    builds_ruby_object_internally: true
    fields:
      - name: type_params
      - name: type
      - name: block
      - name: location
  - name: RBS::Namespace
    builds_ruby_object_internally: true
    fields:
      - name: path
      - name: absolute
  - name: RBS::TypeName
    builds_ruby_object_internally: true
    fields:
      - name: namespace
      - name: name
  - name: RBS::Types::Alias
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: args
      - name: location
  - name: RBS::Types::Bases::Any
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Bool
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Bottom
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Class
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Instance
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Nil
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Self
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Top
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Bases::Void
    builds_ruby_object_internally: true
    fields:
      - name: location
  - name: RBS::Types::Block
    fields:
      - name: type
      - name: required
      - name: self_type
  - name: RBS::Types::ClassInstance
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: args
      - name: location
  - name: RBS::Types::ClassSingleton
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: location
  - name: RBS::Types::Function
    fields:
      - name: required_positionals
      - name: optional_positionals
      - name: rest_positionals
      - name: trailing_positionals
      - name: required_keywords
      - name: optional_keywords
      - name: rest_keywords
      - name: return_type
  - name: RBS::Types::Function::Param
    builds_ruby_object_internally: true
    fields:
      - name: type
        c_type: rbs_node_t *
      - name: name
      - name: location
  - name: RBS::Types::Interface
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: args
      - name: location
  - name: RBS::Types::Intersection
    builds_ruby_object_internally: true
    fields:
      - name: types
      - name: location
  - name: RBS::Types::Literal
    builds_ruby_object_internally: true
    fields:
      - name: literal
      - name: location
  - name: RBS::Types::Optional
    builds_ruby_object_internally: true
    fields:
      - name: type
      - name: location
  - name: RBS::Types::Proc
    builds_ruby_object_internally: true
    fields:
      - name: type
      - name: block
      - name: location
      - name: self_type
  - name: RBS::Types::Record
    builds_ruby_object_internally: true
    fields:
      - name: all_fields
      - name: location
  - name: RBS::Types::Tuple
    builds_ruby_object_internally: true
    fields:
      - name: types
      - name: location
  - name: RBS::Types::Union
    builds_ruby_object_internally: true
    fields:
      - name: types
      - name: location
  - name: RBS::Types::UntypedFunction
    fields:
      - name: return_type
  - name: RBS::Types::Variable
    builds_ruby_object_internally: true
    fields:
      - name: name
      - name: location
  - name: RBS::Types::ZzzTmpNotImplemented
    expose_to_ruby: false
    fields: []
